README.md

`claim.schema.json` is defined in
`github.com/redhat-nfvpe/test-network-function-claim`.  As part of the hectic
preparation to release `v1.0.0`, the location of `claim.schema.json` was moved
to the `schemas` directory as a part of #15:
https://github.com/redhat-nfvpe/test-network-function-claim/pull/15
This change adapts `test-network-function` to utilize the new location of the
`claim.schema.json` file.

Fix a broken link to claim.schema.json

---

README.md
schemas/generic-test.schema.json

Fixes some remanents left over from renaming the default branch to "main".

Improve branching vernacular

---

Makefile
README.md

The targets are named `update-deps` and `install-tools` but were
not correctly referenced in the README or as `.PHONY` targets.
This change corrects the `.PHONY` target names and puts the correct
targets in the README.

document correct dependency make targets

---

pkg/tnf/handlers/ping/ping.go
pkg/tnf/handlers/ping/ping_test.go

ping.go utilizes the binary executable `ping` with a `-c` count.
This means that the ping is non-continuous, and will eventually end
if the destination is unreachable.  Thus, entering an additional CTRL_C
will cause the expecter to exit the oc session.

Let ping.go tnf.Test end naturally

---

pkg/tnf/handlers/base/redhat/version.go
pkg/tnf/handlers/base/redhat/version_test.go

Allow for non-Server container base images.

Allow non-Server release versions of RHEL

---

go.mod
go.sum
pkg/tnf/testcases/base.go
test-network-function/container/suite.go
test-network-function/generic/suite.go
test-network-function/operator/suite.go

ginkgo 1.5.0 allows multiple focus strings. This change includes a backwards-compatible (on our side) change to our code to support this, without necessitating any changes to existing docs or tooling at this time.

upgrade dependencies ginkgo, gomega, gomock

---

cmd/oc/main.go
cmd/ping/main.go
cmd/ssh/main.go
pkg/tnf/test.go

A recent change to use `0` as the ERROR value for test result meant
that some components were reporting a success when they had failed.
This change adds a map to transform the value of test result to a
meaningful Unix exit code.

add a mapping for test result code to Unix return code

---

Dockerfile

The JSON test files were not included in the image, making them
un-runnable.
In addition this also explicitly sets the SHELL env var which is
required by `interactive.SpawnShell` to find a shell to spawn.

fix image env and add json tests

---

test-network-function/generic/suite.go

Must not begin with 'openshift-' and can not be equal to 'default'
https://issues.redhat.com/browse/CTONET-780

Test CNF pod namespace

---

README.md
run-container.sh

Simplifies the `run-container.sh` script's interface by allowing the user to omit specifying the path to the kubeconfig file.
The script will perform actions to autodiscover an existing configuration.
These changes make the `-k` parameter optional.
Including the autodiscovery process, the local kubeconfig lookup order is as follows:
1. If -k is specified, use the paths provided with the -k option.
2. If -k is not specified, use paths defined in `$KUBECONFIG` on the underlying host.
3. If no paths are defined, use the default kubeconfig file located in `$HOME/.kube/config`.
To address the common case of using multiple kubeconfigs in the `$KUBECONFIG` environment variable, support for supplying more than one kubeconfig file has been added.
Each provided local kubeconfig file is mounted to …

Add autodiscovery for local kubeconfig files

---

pkg/config/cnf.go
pkg/config/cnf_test.go
test-network-function/cnf_test_configuration.yml

These config options are not used in functional code, and
serve only to confuse the configuration.

remove ununsed configuration options

---

pkg/tnf/dependencies/binaries.go
pkg/tnf/handlers/nodeport/doc.go
pkg/tnf/handlers/nodeport/nodeport.go
pkg/tnf/handlers/nodeport/nodeport_test.go
pkg/tnf/identifier/identifiers.go
test-network-function/generic/suite.go

We want to make sure that CNF does not use services of type NodePort
https://issues.redhat.com/browse/CTONET-781

Test NodePort services do not exist

---

README.md
pkg/config/cnf.go
pkg/config/example.yaml
pkg/tnf/handlers/operator/operator_test.go
pkg/tnf/testcases/base_test.go
pkg/tnf/testcases/data/operator/operator.go
pkg/tnf/testcases/files/operator/operatorstatus.yml
test-network-function/cnf_test_configuration.yml
test-network-function/operator/suite.go
test-network-function/testconfigure.yml

In order to make sure that an operator was installed via OLM we need to check whether Subscription was created for the operator. This PR adds `SUBSCRIPTION_INSTALLED` test case to existing operator tests.
Related-To: https://issues.redhat.com/browse/CTONET-782
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

CTONET-782 - Subscription verification

---

README.md
pkg/tnf/interactive/spawner.go

Buffer sizes cannot be made variable.  This is an unfortunate limitation of
the PTY library used by google/goexpect.  The issue is rooted in the fact that
a PTY is treated like a file that is not meant to close (receive io.EOF)
between commands.
As such, a configuration knob was added to allow setting interactive.BufferSize
for each interactive context.  If a client does not supply a BufferSize, then
the default is determined.
The default is determined by attempting to read the TNF_DEFAULT_BUFFER_SIZE
environment variable, and then parsing the result as an int.  If the
environment variable is not set or cannot be parsed as an int, then a const
default is used (16KB).
Additionally, this PR adds documentation to the README explaining the situation
in which the default buffer size may need …

Add configuration and documentation surrounding buffer sizes

---

.golangci.yml

this  request is to eliminate the warning from {make lint}
level=warning msg="[runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. "

removing the "interfacer" linter from .golangci.yml

---

README.md
pkg/config/example.yaml
pkg/tnf/handlers/operator/operator_test.go
pkg/tnf/testcases/base_test.go
pkg/tnf/testcases/data/operator/operator.go
pkg/tnf/testcases/files/operator/operatorstatus.yml
test-network-function/testconfigure.yml

In this test we check whether `clusterPermissions` are set for specific `ClusterServiceVersion` is installed. We test etcd operator which is not using the permissions but this tests enable us to check whether operator in test is using `privileged` and in this case we should fail and analyze why such permission is needed.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

CTONET-645 - scc verification

---

README.md
run-container.sh

Allows the end user to choose a custom TNF image with an optional `-i` parameter.
This makes using a locally built TNF image finally possible.
Additionally, the `-i` parameter can be used to run a different version of the TNF image, or an image from another registry.
If the origin of the given image cannot be verified, a warning message is shown to protect the end user from pulling a wrong image by mistake.
The implementation of the check is naive. It's designed to help with debugging image name misspellings, it does not verify if the pulled TNF image has been tampered with or not.

Add an optional parameter -i to run-container.sh

---

pkg/tnf/handlers/deployments/deployments.go
pkg/tnf/handlers/deployments/deployments_test.go
pkg/tnf/handlers/deployments/doc.go
pkg/tnf/handlers/deploymentsdrain/deploymentsdrain.go
pkg/tnf/handlers/deploymentsdrain/deploymentsdrain_test.go
pkg/tnf/handlers/deploymentsdrain/doc.go
pkg/tnf/handlers/deploymentsnodes/deploymentsnodes.go
pkg/tnf/handlers/deploymentsnodes/deploymentsnodes_test.go
pkg/tnf/handlers/deploymentsnodes/doc.go
pkg/tnf/identifier/identifiers.go
test-network-function/generic/suite.go

Read the CNF namespace's deployments
Drain at least one node that is executing deployment pods
https://issues.redhat.com/browse/CTONET-877

ensure a CNF is usable after cordoning a node

---

CONTRIBUTING.md
DEVELOPING.md

5430a4c incorrectly removed some documentation of unit tests
for TNF tests in the process of re-working parts of the
documentation.
This fixes that omission by re-introducing the strong requirement
for unit test coverage.

fix documentation issue introduced in 5430a4c

---

go.mod
go.sum
run-cnf-suites.sh
test-network-function/suite_test.go

Ginkgo has added junit support to the core so the custom
reporters are no longer needed and can be removed.

removing custom ginkgo reporters

---

test-network-function/operator/suite.go

An error in rebasing a change to flow control resulted in
some operator tests being run twice. This change restores
the intended operation.
The error occurred in rebasing prior to merging
d2275b183dd8842d4d74ee198f6391903b47f198
and resulted in some of the changes from commit
5811e2c6cc1670908803407817c6ef3311e1e909
being lost. Luckily the main manifestation of the
error was to cause each test to be run twice rather
than anything more serious.

fix a bug that caused each operator test to run twice

---

pkg/tnf/handlers/operator/operator_test.go
pkg/tnf/testcases/data/operator/operator.go
pkg/tnf/testcases/files/operator/operatorstatus.yml
test-network-function/tnf_config.yml

In case when resourceNames is not defined we returned empty string which failed the test. This PR checks whether there are no resource names and make sure we use well know token `EMPTY` to indicate this. The token was introduced to help validate whether path to
``` json
.spec.install.spec.clusterPermissions[].rules[].resourceNames
```
is valid. In order to use command introduced by this test in a test description we can use action deny with expectedstatus `privileged`.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

CTONET-645 - fix empty resourceNames

---

README.md
run-container.sh

This change adds an optional -n parameter to run-container.sh allowing to set network settings consumed by a `--network` parameter of the `docker run` command responsible for creating the TNF container.
The network mode defaults to `bridge`, consistent with the equivalent setting provided by the `docker run` command.
The documentation, and the usage prompt have been updated to explain the usage of the -n parameter.
Due to the increase in the number of options available, the list of optional arguments in the documentation is now sorted alphabetically.

Add network mode settings to run-container.sh

---

CONTRIBUTING.md
README.md
docs/config.md
pkg/config/autodiscover/autodiscover.go
pkg/config/autodiscover/autodiscover_generic.go
pkg/config/autodiscover/doc.go
pkg/config/autodiscover/pod_info.go
pkg/config/autodiscover/pod_info_test.go
pkg/config/autodiscover/testdata/testorchestrator.json
pkg/config/autodiscover/testdata/testtarget.json
pkg/config/config.go
pkg/config/configsections/certified_request_test.go
pkg/config/configsections/container_config.go
pkg/config/configsections/container_test.go
pkg/config/configsections/generic_config.go
test-network-function/container/suite.go
test-network-function/generic/suite.go
test-network-function/operator/suite.go

This establishes the patterns and approaches for label- and annotation- -based config from the cluster by implementing it for the `generic` spec.

Automatically configure generic spec

---

run-container.sh

When `-n` was given, an unquoted variable in `echo` would break a debug message, as `-n` in echo is responsible for stripping trailing newlines.

Fix debug messages for run-container.sh

---

Dockerfile

The Dockerfile instructions involved created symlinks to `generic_test_configuration.yml` and `cnf_test_configuration.yml`, which have been replaced with a consolidated `tnf_config.yml` file.
From now on, the Dockerfile uses the `TNF_CONFIGURATION_PATH` environment variable to set the path to the `tnf_config.yml` file.

Fix tnf_config.yml missing in TNF container

---

.github/workflows/pre-main.yaml

Adds a new `smoke-tests` job to the existing `pre-main.yaml` workflow.
The included Smoke Tests consist of running the diagnostic test suite against the `local-test-infra` minikube test cluster, both on the host (using the `run-cnf-suites.sh` script), and in a TNF container via the `run-container.sh` script.

Extend pre-main.yaml CI workflow with Smoke Tests

---

.github/workflows/tnf-image.yaml

This change adds a `tnf-image.yml` workflow that first fetches the version number of the latest relase from the generic version branch (e.g. `1.0.x`), builds the image, performs smoke tests, and then publishes the new container image to Quay.io.
The workflow can be triggered by publishing a new release, or by manually dispatching it via the `workflow_dispatch` feature built into GitHub.
To automatically apply security patches provided in UBI, an additional cron trigger will ensure that the workflow is run and the image is rebuilt once a day.

Add automatic publishing of TNF container images

---

examples/example_config.yaml
pkg/config/testdata/tnf_test_config.yml
test-network-function/tnf_config.yml

In restructuring the configuration file to separate the certification
information from the cluster resource information, these configuration
files were not completely updated. This change remedies that.

correct example config files

---

.github/workflows/tnf-image.yaml

The workflow's execution will be skipped if run outside of test-network-function.

Disable `tnf-image.yaml` workflow on forked repos

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml

The `pre-main.yaml` workflow is updated to automatically push an unstable image to Quay.io.
The image is built from the `main` branch.

Add automatic publishing of unstable TNF images

---

test-network-function/generic/suite.go

The test uses a custom `MachineConfig` resource that is not available
on minikube.

Disable kernel boot params test on minikube

---

CATALOG.md
cmd/catalog/cmd/data/INTRO.md
cmd/catalog/cmd/data/TEST_CASE_BUILDING_BLOCKS_CATALOG.md
cmd/catalog/cmd/data/TEST_CASE_CATALOG.md
cmd/catalog/cmd/generate.go
test-network-function/container/suite.go
test-network-function/diagnostic/suite.go
test-network-function/identifiers/identifiers.go
test-network-function/operator/suite.go

Augment the catalog generation to include the test information.
Additionally, regenerate CATALOG.md to include all the new great
tests that were added in CNF Certification 2.0.
Additionally, implement results recording for non-generic test
suites.

Create descriptions/remediations for each JUnit test case

---

pkg/tnf/handlers/deploymentsnodes/deploymentsnodes_test.go
pkg/tnf/handlers/owners/owners.go
pkg/tnf/handlers/owners/owners_test.go

The generic test suite was failing the Pod ownership test.  This change
resolves a few issues with the test including:
1) The ReelFirst() regular expression was made to be more specific.  Namely,
the test now expects the proper "OWNERKIND" header, and parses output after
ignoring the header line.
2) The "-o custom-columns"... line was modified to properly escape brackets and
the asterisk character.  In many versions of `oc`, these characters must be
either quoted or escaped.
3) Existing positive unit tests seeded test data from the negative test cases.
This change switches to accurate positive test data mock output.
Additionally, the requirement of an exact match is dropped due to the fact
that trailing newlines may occur with the modified regular expression from
step 1.
I have tested …

CTONET-999: Resolves issues with generic test suite

---

README.md
run-container.sh

Resolves #238.
There are a whole host of issues with using "podman" on many non-linux
Operating Systems.  For example, support in macOS currently involves federation
with a remote linux based server.  As such, we should support multiple
platforms and allow the use of alternative container virtualization clients.
This change adds the auto-detection of a user-specified container
virtualization client through the TNF_CONTAINER_CLIENT environment variable.
If the user does not set the variable, then "podman" is used by default.
Additionally, documentation was added to give an example of how to use
"docker" instead of "podman".

Explicitly allow use of "docker" instead of "podman"

---

README.md

Link the available tests in README.md so people actually
know what tests we include.

Add a link to CATALOG.md in README.md

---

cmd/claim/main.go
pkg/junit/convert.go
pkg/junit/convert_test.go
run-cnf-suites.sh
test-network-function/suite_test.go

After today's presentation, it became clear that the main entrypoint to our
test suite (suite_test.go's TestTest) was extremely messy.  As such, this
commit cleans up the entrypoint by:
* abstracting several helper methods to decrease the complexity of TestTest()
* Renaming the `ExportJunitAsJSON` to `ExportJUnitAsMap`, which is
linguistically more accurate.
* Eliding useless variables in places.
* Eliding the "-report" flag, as it wasn't actually used for anything.

Cleanup suite_test.go

---

pkg/tnf/reel/reel.go
pkg/tnf/reel/reel_test.go
pkg/tnf/test.go
pkg/tnf/test_test.go

CTONET-1013 and CTONET-1011 both share a common problem;  it appears that
results are being truncated.  This is true, but it is supposed to happen.  The
way `expect` works is to return the first match of a given regular expression.
Even if greedy quantifiers such as `*` are utilized, google/goexpect is based
on copying an output buffer every so often (the interval is identified by
chkDuration duration.Duration in goexepct).
As such, consider the following regular expression:
`(?s).+`
This could match something as simple as:
`BeginningOfTheOutput...`
When the user fully intended to capture:
```
BeginningOfTheOutput...
EndOfTheOutput
```
The problem compounds for situations in which the command output is arbitrary
in length, and could very well not end with a sentinel at all.  In typical …

Automatic terminal prompt emulation

---

pkg/tnf/handlers/nodemcname/nodemcname.go

The provided command was not producing any output, as there was an issue with
quotations and escaping.  This change utilizes a new command which does produce
the intended output.  This change was tested in New Mexico:
```
2021/06/09 17:54:37 Sent: "oc get node worker-113 -o json | jq '.metadata.annotations.\"machineconfiguration.openshift.io/currentConfig\"' && echo END_OF_TEST_SENTINEL\n"
2021/06/09 17:54:37 Match for RE: ".+((.|\n)*END_OF_TEST_SENTINEL\n)" found: ["\"rendered-worker-db680ffdf57f50623cf602c0a665d755\"\nEND_OF_TEST_SENTINEL\n" "\nEND_OF_TEST_SENTINEL\n" "\n"] Buffer: "\"rendered-worker-db680ffdf57f50623cf602c0a665d755\"\nEND_OF_TEST_SENTINEL\n"
```
As seen above, the corrected "rendered-worker-XXXX" machine config set is
extracted and returned.
Signed-off-by: Ryan …

Resolves issue in the command to derive machineconfig set for a node

---

test-network-function/container/suite.go
test-network-function/operator/suite.go

Only query for container/operator certification when they are present.  This
ultimately makes these sections of config optional.

Query for operator/container certification only when present

---

CATALOG.md
pkg/tnf/handlers/checksubscription/check-subscription.json
pkg/tnf/handlers/checksubscription/checksubscription_test.go
pkg/tnf/handlers/checksubscription/doc.go
pkg/tnf/identifier/identifiers.go
pkg/tnf/testcases/base.go
pkg/tnf/testcases/base_test.go
pkg/tnf/testcases/data/operator/operator.go
pkg/tnf/testcases/files/operator/operatorstatus.yml
test-network-function/identifiers/identifiers.go
test-network-function/operator/suite.go

Hitherto, the operator subscription is tested against a non-templated
test case input file.  The existing framework does not have the innate
ability to render the file contents based on a template, making it an
unsuitable candidate for a test which requires specific, templated output.
Since test cases ultimately are fed into the tool using a Go string,
templating this code seemed like the wrong solution.
This change rips the "CHECK_SUBSCRIPTION" test out of the existing operator
testing framework.  That framework is difficult to maneuver, and this change
aligns with utilizing the JSON test framework instead.  Why was this approach
chosen?  Here are some of the reasons:
1) Standardize on JSON Test Template framework.
2) Disaggregate the reference to the "operator-is-installed-via-olm" from …

Resolves issues with checking operator subscription

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml

Previously, the CI workflows would use `docker` to build and push new container images, while `run-tnf-container.sh` invoked `podman` to run the built images, which would result in unexpected failures of selected workflows.
This change introduces:
- a `localhost/` prefix to images that are meant for local consumption
- a $TNF_CONTAINER_CLIENT environment variable set to `docker`
- the use of `ubuntu-20.04` (instead of latest), to enforce consistency across all workflows

Force CI Workflows to use docker for all tasks

---

CATALOG.md
test-network-function/identifiers/identifiers.go

Improvement in the categorization of the test cases: "list-cni-plugins" and "nodes-hw-info" moved from "generic" TS to "diagnostic".
This commit changes the identifiers.go file only, but the automatically rebuilt file catalog.mds needs to be commited as well to reflect the change.

Fix test identifiers for list-cni-plugins and nodes-hw-info TCs (was under generic instead of diagnostic)

---

pkg/tnf/testcases/base.go
pkg/tnf/testcases/data/cnf/privilegedpod.go

The ROOT_CHECK of the access-control TS failed with some valid uid
combinations like:
- 1000640000 --> reported by Ramón Pérez <raperez@redhat.com>
- 1001       --> classic uid used linux/kuberentes examples.
- 001

Fixed NON_ZERO regex

---

test-network-function/diagnostic/suite.go

Local function diagnostic.isMinikube() is a copy of the
common.IsMinikube() one, so it can be deleted.

Use the common.IsMinikube() function inside diagnostic TS.

---

pkg/tnf/testcases/data/cnf/privilegedpod.go

Using Go template to to look for hostpath volumes. If <no value> is reported one or more times, the test passes. Otherwise the test fails.

Fix for HostPath test 

---

cmd/generic/cmd/jsontest.go
cmd/ssh/main.go
pkg/config/config.go
pkg/tnf/interactive/spawner.go
test-network-function/common/env.go

This aims to add timeout to "Send" function in goexpect library, by default, the library does not use any timeout. 
By looking in the code of the goexpect,  it's printing the log after "sending" the command, so if there's any issue in the "send" we will not see the log. This seems like the issue we were seeing this morning where the process hangs.

add default timeout to send command in spawned shell

---

pkg/tnf/interactive/spawner.go

Calls to (*expecter).Send() will fail if the shell process has already
exited.

Spawner Check function implementation.

---

DEVELOPING.md
cmd/tnf/main.go
pkg/tnf/handlers/handler_template/handler.tmpl
pkg/tnf/handlers/handler_template/handler_test.tmpl

Fixed so the tnf tool can be launched anywhere. If no envar
TNF_HANDLER_SRC detected, the tool assumes you're in the repo root
folder so the handlers folder should be at ./pkg/tnf/handlers.
+ Minor refactors.

TNF handler generation tool improvements.

---

pkg/config/autodiscover/pod_info.go

This fixes the abort issue after drain test failure due to limited resource

Skip pods not in Running state in discovery

---

pkg/tnf/testcases/data/cnf/privilegedpod.go
pkg/tnf/testcases/files/cnf/privilegedpod.yml

Previously, this `jq` command was failing to find the hostPort references because `ports` is an array.
Marked WIP until I can test thoroughly.

Fix jq hostPort lookup

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
Dockerfile

Go 1.17.3 is now [available](https://twitter.com/golang/status/1456314310330880004).
Includes security fixes to archive/zip and debug/macho (CVE-2021-41772, CVE-2021-41771).

Go 1.17.3 update

---

pkg/tnf/handlers/rolebinding/rolebinding.go

When several namespaces exist in a cluster  and the namespace under test is the prefix of another namespace in the same cluster, the rolebinding test fails. for instance:
if namespace under test is tnf and another namespace tnf1 exists with pods deployed the role binding test fails in namespace tnf. This is because the regex does not mach "whole words" and thinks tnf1 is a match for namespace tnf

Fix rolebinding result parsing

---

pkg/config/config.go

The CRD autodiscovery was removed by mistake in this commit:
03b5d5c464d40279ab8bcb09ad20ab72014a056f (PR:
https://github.com/test-network-function/test-network-function/pull/395)

Restore CRDs autodiscovery.

---

pkg/tnf/testcases/data/cnf/privilegedpod.go
pkg/tnf/testcases/files/cnf/privilegedpod.yml

```
$ oc get pod busybox1 -o json | jq -r '.spec.containers[0] | select(.ports) | .ports[].hostPort'
null
```
We want to avoid the `null` so switching to go-template:
```
$ oc get pod busybox1 -o go-template='{{range (index .spec.containers 0).ports }}{{if .hostPort}}{{.hostPort}}{{end}}{{end}}'
```
Will review with @greyerof on Monday.

Use go template for hostPort check

---

.github/workflows/tnf-image.yaml

This is to start building tnf release images on the 3.1.x branch. Also removing the 3.0.x branch from the matrix list since it no longer builds due to ginkgo 1.16 requirement (will be fixed by implementing a new branch strategy)

remove 3.0.x branch(due to failure to build), add 3.1.x branch to matrix

---

CATALOG.md
pkg/tnf/identifier/identifiers.go

It was pointing to the nodehugepagesIdentifierURL, instead of the
nodeselector IdentifierURL.

Fix URL for node selector identifier

---

CONTRIBUTING.md

The CONTRIBUTING.md file had an outdated list of core reviewers, and
provided a non-working command to run unit tests.

Update CONTRIBUTING.md to reflect current status

---

.github/workflows/pre-main.yaml

We want to store the test run artifacts for both the smoke and container
tests, so we can analyze them after a CI job.

Archive test run artifacts in GitHub Actions

---

.github/workflows/pre-main.yaml
script/results.html

As part of the CI process, we want to make it easier to check the
claim.json file after a test suite execution.
This commit adds a results.html file, which can parse a claim file and
show its output in a human-readable way.

Add static HTML page to visualize claim.json

---

pkg/tnf/handlers/containerid/containerid_test.go

The `containerid` package was missing unit test coverage.

Add unit tests for containerid package

---

test-network-function/networking/suite.go

Skipping all container with no multus IPs
If no container available in the end, skipping the test

Fixing Multus skip logic

---

test-network-function/accesscontrol/suite.go

+ Avoid combo TC to stop when one pod fails the TC.
+ Improved error logging, including the command that was sent and the
expectations for the failing TC.

Combo TC improvements.

---

.github/workflows/pre-main.yaml
Dockerfile
run-cnf-suites.sh
script/results.html

To simplify log viewing, we want to have the CI job insert the
claim.json file automatically inside the results.html page. This cannot
be done by dynamically loading it due to CORS restrictions, but we can
convert the JSON file into a javascript file, then load it from the HTML
page.

Insert claim.json file in results HTML page

---

pkg/config/autodiscover/autodiscover_targets.go

`FindTestDeploymentsByLabelByNamespace` is unused.  Not sure why the `deadcode` linter is not catching it.

Remove dead func

---

test-network-function/certification/suite.go

Added logic to skip certification tests when test input is not available:
- if there is no operator or cnf to check -> skip the test
- if the tnf_config.yml contains missing test input info as shown below, this particular certification check is not performed (in either the cnf or operator tests):
- operator definitions with empty names or organization
- or cnf definitions with empty names or repositories 
- If input for all cnfs checks is incomplete, the CNF check test is skipped 
- If input for all operator checks is incomplete, the operator check test is skipped

Skipping certification tests when test input not present

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
Dockerfile

https://go.dev/doc/devel/release
`go1.17.4 (released 2021-12-02) includes fixes to the compiler, linker, runtime, and the go/types, net/http, and time packages.`

Update Go to 1.17.4

---

test-network-function/lifecycle/suite.go

In the pod recreation test, when deployments are not restarted in time
after a node is drained, that node would remain drained forever and
never be uncordoned.
We can defer the node uncordon operation, so it will always be executed.
If the node was successfully uncordoned, a second uncordon will become a
no-op.
We also remove some unneeded checks after the call to uncordonNode(),
since they are already performed by waitForAllDeploymentsReady(), and
move the final waitForAllDeploymentsReady() check outside of the loop,
so we only do it once.

Ensure drained nodes are uncordoned if test times out

---

pkg/config/config.go
pkg/tnf/handlers/ipaddr/ipaddr.go

Using the nsenter utility to run the "ip" command from the debug pod in the container namespace. containers that do not have the executable can pass networking tests.
The createContainers() function was split into:
- createContainersNoIP(): populates the container list but does not get the default IP from the containers. Before we were getting the ip from the container oc, now we need to run nsenter with the node oc. But at this moment the list of nodes is not ready yet since it relies on the nodes selected by the CNF replicaset
- recordContainersDefaultIP(): This second part is getting the container default IP after the node and container lists are established using nsenter and node oc.

removing dependency on ip utility (via nsenter)

---

pkg/utils/utils_test.go

Added some unit tests for:
- `ArgListToMap`
- `FilterArray`
- `AddNsenterPrefix`
There are other functions that boil down to the `Reel` package again and I'm not sure about how to unit test those at the moment.

Add utils package unit tests

---

test-network-function/accesscontrol/suite.go

[1] introduced a small issue, where the test is executed twice, once
using RunAndValidateWithFailureCallback() and once with
RunWithCallbacks(). We only need the latter, which has a better logging
output.
[1] - https://github.com/test-network-function/test-network-function/pull/508

Run cluster role binding test once per pod

---

test-network-function/common/env_test.go

There are a few functions that I didn't attempt to unit test:
- `TcClaimLogPrintf`
- `GetContext`
- `SetLogFormat`

Add unit tests for common/env

---

CATALOG.md
test-network-function/diagnostic/suite.go
test-network-function/identifiers/identifiers.go

The identifier "TestClusterVersionIdentifier" was used twice as key for
the CATALOG entry.

CATALOG: Restore Cluster CSI info TC.

---

.github/workflows/pre-main.yaml
.gitignore
Makefile

Setting a minimum unit test threshold of 60%.  Our current testing coverage is 67%.  We can bump the threshold up later as the coverage improves.
Tutorial: https://medium.com/citihub/how-to-set-up-a-test-coverage-threshold-in-go-and-github-167f69b940dc
As a bonus, I added `make coverage-html` to output a browser based coverage report.

Add unit test coverage gate

---

internal/api/api.go
pkg/config/autodiscover/autodiscover.go
pkg/config/autodiscover/autodiscover_targets.go
pkg/config/autodiscover/autodiscover_test.go
pkg/config/autodiscover/csv_info.go
pkg/config/autodiscover/pod_info.go
pkg/config/configsections/container.go
test-network-function/accesscontrol/suite.go
test-network-function/networking/suite.go

Related to: https://issues.redhat.com/browse/CNFCERT-249
Naked returns are less explicit and less readable and to be consistent across our code we should probably stop using them.

Removing naked returns

---

test-network-function/diagnostic/suite.go

The ifconfig utility is deprecated in RHEL [1] and could be removed in
future releases. When gathering network information from nodes, we
should use "ip".
This commit changes the diagnostic-nodes-hw-info test to use "ip a"
instead of ifconfig, and adjusts output parsing to match the
differences.
[1] - https://access.redhat.com/articles/1179833

Replace usage of ifconfig with ip

---

pkg/config/autodiscover/autodiscover.go
pkg/config/autodiscover/autodiscover_debug.go
pkg/config/autodiscover/autodiscover_targets.go
pkg/config/autodiscover/autodiscover_test.go
pkg/config/autodiscover/container_test.go
pkg/config/config.go
pkg/config/configsections/common.go
pkg/config/configsections/config_section_test.go
pkg/config/configsections/container.go
pkg/config/configsections/pod.go
test-network-function/accesscontrol/suite.go
test-network-function/diagnostic/suite_test.go
test-network-function/lifecycle/suite.go
test-network-function/networking/suite.go
test-network-function/platform/suite.go

Stores the context of one container in the pod object to get access to the networking namespace of the pod (since all container share the same net namespace). 
The networking tests are now ran per pod instead of per container

Make the networking tests run once per pod instead of once per container

---

CATALOG.md
test-network-function/identifiers/identifiers.go

The `automountServiceAccountToken` section in the README didn't have a reference to the best practice document and section which it was referenced.

Add best practice ref for automount token

---

CATALOG.md
cmd/tnf/generate/catalog/catalog.go

Since we are now using test labels for all test cases, it is a good idea
to include them in the generated CATALOG.md file.
This will allow us to easily check the test labels in case we want to
filter certain tests.

Add test label to catalog

---

CATALOG.md
test-network-function/identifiers/identifiers.go
test-network-function/networking/suite.go

Previously, the networking ICMPv4 connectivity tests for the default and
Multus networks shared the same id. This commit splits that, so each
test case has a single id.
Fixes #576

Update multus networking TC id

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
Dockerfile

Go 1.17.6 is now available.
https://twitter.com/golang/status/1479199301352013829
From their release page:
```
go1.17.6 (released 2022-01-06) includes fixes to the compiler, linker, runtime, and the crypto/x509, net/http, and reflect packages. See the Go 1.17.6 milestone on our issue tracker for details.
```

Update Go to 1.17.6

---

cmd/tnf/generate/catalog/catalog.go

Previously, we were not ensuring an order when getting the list of
suites in outputTestCases(). This caused issues, because the CATALOG.md
file could be changed by any PR, breaking order.
Fixes #583

Ensure catalog suites are always ordered

---

.golangci.yml
pkg/tnf/handlers/base/redhat/version.go

`release` was not used and subsequently removed.

Re-enable the unused linter

---

pkg/config/configsections/certified_request_test.go
pkg/config/configsections/common.go
pkg/config/configsections/request.go
pkg/config/testdata/tnf_test_config.yml
pkg/tnf/handlers/nodetainted/nodetainted.go
pkg/utils/utils.go
pkg/utils/utils_test.go
test-network-function/platform/suite.go
test-network-function/platform/suite_test.go
test-network-function/tnf_config.yml

Related to: https://issues.redhat.com/browse/CNFCERT-204
If a node encounters a tainted kernel failure only pertaining to `module was loaded`-type errors, then the code will compare the list of loaded/out-of-tree modules to see if they are allowed via the configurable allow-list.
Set the allow list in the `tnf-config.yml` such as follows:
```
acceptedKernelTaints:
- module: "taint1"
- module: "taint2"
```
I added to the `test-network-function/tnf_config.yml` configuration file the following allowed tainted modules, vboxsf and vboxguest.  This will "allow" these two modules to taint the kernel and get away with it.  😉 
Marked this as WIP as I work out naming convention, possibly making up some more unit tests/breaking down the function into smaller chunks.

Add allow-list for tainted modules

---

.golangci.yml
Makefile
README.md
test-network-function/platform/suite.go

https://github.com/golangci/golangci-lint/releases/tag/v1.44.0
The v1.44.0 linter caught a line in test-network-function/platform/suite.go so I fixed that as well.

Bump GolangCI-lint to 1.44.0

---

test-network-function/diagnostic/suite.go

Currently, some plugins appear without name, so the information seems not very relevant:
This PR adds the type field to the CNI plugins claim info so the loopback/unnamed plugins can have a more descriptive output.

Add type field to the CNI plugin info in claim file.

---

README.md
pkg/config/autodiscover/autodiscover_targets.go
pkg/config/config.go
pkg/config/configsections/common.go
test-network-function/networking/suite.go

Backport of the new label to skip Multus test (https://github.com/test-network-function/test-network-function/pull/605) on current main (instead of furture IPv6 update)

Backport for skip Multus label support

---

pkg/utils/utils.go

A couple of changes:
- RunCommandInContainerNameSpace was unused.  Removed.
- `docker-pullable` was part of the imageID in my latest version of minikube.  See:
```
"imageID": "docker-pullable://quay.io/testnetworkfunction/debug-partner@sha256:8a9b6370854f37acb25f22177ba4185b04a41100fb482b863817c9642c8dc474",
```

Add case for docker-pullable

---

.github/workflows/tnf-image.yaml

Reverting tag name to latest, it is fine since it is only used locally

Reverting local tag

---

.github/workflows/tnf-image.yaml

Uses available github action to build the test cluster so it should work for partner repo before and after 3.3.0
Fix for: https://github.com/test-network-function/test-network-function/issues/621

Fix image generation after ipv6 merge

---

CATALOG.md
test-network-function/identifiers/identifiers.go
test-network-function/networking/suite.go

It was mistakenly using the nodePort check's one.

Create new test ID for networking's testListenAndDeclared TC

---

pkg/utils/utils.go
pkg/utils/utils_test.go
test-network-function/platform/suite.go

The use of modinfo won't work in cases where modules have been loaded
from inside pods (like in SRO), since those pods have a different
filesystem namespace for /lib/modules.
The ModuleInTree function has been updated to parse the content of the
file /sys/module/<module>/taint, which returns a string with a letter
per taint. The taint <-> letter correspondence list can be found here:
- https://github.com/torvalds/linux/blob/master/kernel/panic.c#L369
- https://www.kernel.org/doc/html/latest/admin-guide/tainted-kernels.html
Some log traces improved.

ModuleInTree function modified to use /sys/module/<mod>/taint

---

Makefile
README.md

https://github.com/golangci/golangci-lint/releases/tag/v1.44.1
No code changes found/needed.

Bump GolangCI-lint to v1.44.1

---

.github/workflows/pre-main.yaml
Makefile
test-network-function/platform/suite_test.go
test-network-function/suite_test.go

This fix allows for running all units tests:
- The main entry point for the suite is a unit test, so needs to be excluded.
- quality gate adjusted to 50%
- fixed unit test

Fix for unit testing and test coverage (backport from new repo)

---

test-network-function/platform/suite.go

As I was [writing unit tests](https://github.com/test-network-function/cnf-certification-test/pull/63) for the "new" repo, I came across this bug where we would only flag the node as failed if it failed because of a `module was loaded` reason.

Bug fix: kernel tainted test did not fail on other types of failures

---

.golangci.yml
Makefile
README.md

https://github.com/golangci/golangci-lint/releases/tag/v1.45.2
Similar to:
https://github.com/test-network-function/cnf-certification-test/pull/92
https://github.com/test-network-function/test-network-function-claim/pull/41
https://github.com/test-network-function/cnfcert-tests-verification/pull/55

Update GolangCI to 1.45.2

---

CATALOG.md
test-network-function/identifiers/identifiers.go
test-network-function/lifecycle/suite.go

Due to the issues on both the original and current implementation,
the terminationGracePeriod TC will be removed.
A new and improved version of this TC should be done in the new repo,
checking that after the configured (or defaulted) value, the pods were 
removed without any exit error code.

lifecycle's terminationGracePeriod TC removed.

---

.github/workflows/pre-main.yaml
Dockerfile
Makefile

- Bumping installed Helm version to match the new repo's [changes](https://github.com/test-network-function/cnf-certification-test/pull/127).
- Found in the new repo that the version of ginkgo is [not correct](https://github.com/test-network-function/cnf-certification-test/pull/130).  Fixing that here too.

Fix missed version changes

---

test-network-function/platform/suite.go

Used in test platform-alteration-sysctl-config

Fix the regex used to parse the sysctl config params
