- .github/workflows/pre-main.yaml
> rename master to main in workflow

- README.md
- run-cnf-suites.sh
- test-network-function/suite_test.go
> Add flag to control claim output location

- pkg/tnf/reel/reel.go
Rename the reel.Reel receivers from reel to r.
> Rename reel.Reel receivers

- Makefile
Invoke make mocks prior to go mod tidy && go mod vendor.
> Fix update-deps Makefile target

- Dockerfile
- README.md
- go.mod
- go.sum
- pkg/tnf/testcases/base.go
- run-cnf-suites.sh
- run-container.sh
- test-network-function/container/suite.go
- test-network-function/generic/suite.go
- test-network-function/operator/suite.go
Adds a dockerfile, helper, and docs for running the tests in a container.
> Containerised tests

- README.md
- run-container.sh
> add link to quay.io in container docs and runner

- internal/api/api.go
- internal/api/api_test.go
- test-network-function/operator/suite.go
Note the issue resolved by the first commit as it does not show in the overall diff.
> Fix order of args in Catalog APIs

- .github/workflows/merge.yaml
- README.md
> add in a merge job and corresponding badge

- .github/workflows/merge.yaml
> run "build" job on merge

- README.md
> Include go report card

- DEVELOPING.md
> add short discussion of Go Templates to docs

- pkg/config/turnium.go
- pkg/tnf/dependencies/binaries.go
- pkg/tnf/identifier/identifiers.go
- run-cnf-suites.sh
- test-network-function/generic_test_configuration.yml
- test-network-function/suite_test.go
- test-network-function/turnium-test-configuration.yml
- test-network-function/turnium/doc.go
- test-network-function/turnium/suite.go
- test-network-function/turnium/turnium.json
Also add license to `diagnostic` package
> add Turnium test for link status

- CONTRIBUTING.md
> Add Charlie Wheeler-Robinson to the committers list

- pkg/tnf/handlers/clusterrolebinding/clusterrolebinding.go
- pkg/tnf/handlers/clusterrolebinding/clusterrolebinding_test.go
- pkg/tnf/handlers/clusterrolebinding/doc.go
- pkg/tnf/handlers/rolebinding/doc.go
- pkg/tnf/handlers/rolebinding/rolebinding.go
- pkg/tnf/handlers/rolebinding/rolebinding_test.go
- pkg/tnf/handlers/serviceaccount/doc.go
- pkg/tnf/handlers/serviceaccount/serviceaccount.go
- pkg/tnf/handlers/serviceaccount/serviceaccount_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/generic/suite.go
We read pod's service account and use it to understand the roles it
binds to
https://issues.redhat.com/browse/CTONET-780
> CTONET-780 - Test pod priviliges

- .github/workflows/pre-main.yaml
- Makefile
- pkg/tnf/handlers/nodeport/nodeport.go
> Fix problems with the linter workflow

- README.md
> Add documentation surrounding excluding containers from the connectivity suite

- pkg/tnf/dependencies/binaries.go
- pkg/tnf/handlers/nodenames/doc.go
- pkg/tnf/handlers/nodenames/nodenames.go
- pkg/tnf/handlers/nodenames/nodenames_test.go
- pkg/tnf/handlers/nodetainted/doc.go
- pkg/tnf/handlers/nodetainted/nodetainted.go
- pkg/tnf/handlers/nodetainted/nodetainted_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/generic/suite.go
https://issues.redhat.com/browse/CTONET-844
> Test that node kernels are not tainted

- pkg/tnf/handlers/hugepages/doc.go
- pkg/tnf/handlers/hugepages/hugepages.go
- pkg/tnf/handlers/hugepages/hugepages_test.go
- pkg/tnf/handlers/nodehugepages/doc.go
- pkg/tnf/handlers/nodehugepages/nodehugepages.go
- pkg/tnf/handlers/nodehugepages/nodehugepages_test.go
- pkg/tnf/handlers/nodenames/nodenames.go
- pkg/tnf/handlers/nodenames/nodenames_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/generic/suite.go
Verify that CNFs did not change the hugepages configuration.
We use MachineConfig for determining cluster configuration
https://issues.redhat.com/browse/CTONET-860
> Test worker nodes' hugepages

- test-network-function/generic/suite.go
> Previous PR accidently changed timeout

- example-cnf/cr/create.go
- example-cnf/cr/create_test.go
- example-cnf/cr/traffic.go
- example-cnf/cr/traffic_test.go
- example-cnf/suite.go
- example-cnf/test-cr.values.yaml
- example-cnf/test-cr.yaml.tpl
- pkg/tnf/identifier/identifiers.go
- run-cnf-suites.sh
- test-network-function/suite_test.go
> Example CNF CNF-Specific Test Case

- pkg/tnf/handlers/owners/doc.go
- pkg/tnf/handlers/owners/owners.go
- pkg/tnf/handlers/owners/owners_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/generic/suite.go
Verify CNF pods' owners include Deployment or DaemonSet
https://issues.redhat.com/browse/CTONET-884
> Pods should be managed by DaemonSets/Deployments

- examples/example_config.yaml
- test-network-function/generic/suite.go
- test-network-function/tnf_config.yml
> skip fs diff test if no container configured

- DEVELOPING.md
- pkg/tnf/test.go
- test-network-function/suite_test.go
We want to be able to add informational messages to each test
https://issues.redhat.com/browse/CTONET-887
> add extra info per test

- Dockerfile
This is considered an emergent fix in order to unblock the GitHub pipeline.
As such, review comments will be addressed in a follow-up rather than prior to
merging.
ubi8/ubi maintainers recently released a new version of the base container
image, which contains an updated yum manifest.  `golangci-1.14.12` is no
longer a valid package in `latest`.
This change does the following:
0) Checks to ensure the docker image is built on top of `x86_64` architecture.
If not, the build exits with an appropriate error message.
1) Removes the `golang-1.14.12` package from the yum install list.  Since this
package also brought in `gcc` and `krb5-devel`, which are compile-time
dependencies for `oc`, `gcc` and `krb5-devel` were added to the yum install
list.  `oc` would not compile otherwise.  Additionally, …
> Fix broken pipeline

- test-network-function/generic/suite.go
https://issues.redhat.com/browse/CTONET-964
> skip testDeployments if using minikube

- README.md
https://issues.redhat.com/browse/CTONET-975
https://issues.redhat.com/browse/CTONET-973
https://issues.redhat.com/browse/CTONET-972
> document testDeployments testRoles testNamespace

- run-cnf-suites.sh
- test-network-function/suite_test.go
Remove use of deprecated Ginkgo APIs and fix the JunitPath
> Ctonet 883

- test-network-function/diagnostic/doc.go
> Add doc.go for diagnostic package

- test-network-function/generic/suite.go
https://issues.redhat.com/browse/CTONET-991
> log termination grace period warning to extra info

- test-network-function/generic/suite.go
https://issues.redhat.com/browse/CTONET-992
> log node selector/affinity warning to extra info

- .github/workflows/pre-main.yaml
- .github/workflows/tnf-image.yaml
> Extend CI smoke tests with generic test suite

- README.md
Added nodeSelector/nodeAffinity and testGracePeriod to the documentation
> CTONET-971 + CTONET-974

- pkg/tnf/handlers/hugepages/hugepages.go
- pkg/tnf/handlers/hugepages/hugepages_test.go
> Ignore non key/value pairs in kernelArguments

- CATALOG.md
- test-network-function/generic/suite.go
> Disable pod-recreation test

- Makefile
- README.md
- cmd/gradetool/doc.go
- cmd/gradetool/main.go
- pkg/gradetool/doc.go
- pkg/gradetool/gradetool.go
- pkg/gradetool/gradetool_test.go
- pkg/gradetool/testdata/claim-good.json
- pkg/gradetool/testdata/claim-missing-field.json
- pkg/gradetool/testdata/out.json
- pkg/gradetool/testdata/policy-duplicate-grade.json
- pkg/gradetool/testdata/policy-good.json
- schemas/gradetool-policy-schema.json
https://issues.redhat.com/browse/CTONET-765
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>
> gradetool - propose grade from test results

- .github/workflows/tnf-image.yaml
> Enable TNF image publishing for 2.0 release

- CATALOG.md
- pkg/tnf/handlers/owners/owners.go
- pkg/tnf/handlers/owners/owners_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/generic/suite.go
https://issues.redhat.com/browse/CNFCERT-15
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>
> owner of pod must not be DaemonSet

- CATALOG.md
- pkg/tnf/handlers/nodedebug/doc.go
- pkg/tnf/handlers/nodedebug/nodedebug.go
- pkg/tnf/handlers/nodedebug/nodedebug_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/diagnostic/suite.go
- test-network-function/identifiers/identifiers.go
- test-network-function/suite_test.go
https://issues.redhat.com/browse/CNFCERT-24
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>
> add nodes info such as hardware, packages and plugins

- CATALOG.md
- go.sum
- pkg/tnf/dependencies/binaries.go
- pkg/tnf/handlers/logging/doc.go
- pkg/tnf/handlers/logging/logging.json
- pkg/tnf/handlers/logging/logging_test.go
- pkg/tnf/identifier/identifiers.go
- schemas/generic-test.schema.json
- test-network-function/generic/suite.go
- test-network-function/identifiers/identifiers.go
Signed-off-by: salaheddine hamadi <shamadi@redhat.com>
> adding logging test : test if PUT emits logs to stdout/stderr

- CATALOG.md
- Dockerfile
- pkg/tnf/handlers/shutdown/doc.go
- pkg/tnf/handlers/shutdown/shutdown.gotemplate
- pkg/tnf/handlers/shutdown/shutdown.json
- pkg/tnf/handlers/shutdown/shutdown_test.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/container/suite.go
- test-network-function/generic/suite.go
- test-network-function/identifiers/identifiers.go
- test-network-function/suite_test.go
Test if containers define the pre-stop hook for lifecycle management
update Dockerfile
Signed-off-by: salah hamadi <shamadi@redhat.com
> Test if containers define the pre-stop hook for lifecycle management

- .github/workflows/pre-main.yaml
- pkg/config/config.go
- run-cnf-suites.sh
- test-network-function/generic/accesscontrol.go
- test-network-function/generic/certification.go
- test-network-function/generic/lifecycle.go
- test-network-function/generic/networking.go
- test-network-function/generic/observability.go
- test-network-function/generic/platform.go
- test-network-function/generic/suite.go
Markdown files will be updated in subsequent PRs
> CNFCERT-57 Placeholder go files for the new test suites

- go.mod
- go.sum
- pkg/tnf/handlers/csidriver/csidriver.json
- pkg/tnf/handlers/csidriver/csidriver_test.go
- pkg/tnf/handlers/csidriver/doc.go
- pkg/tnf/identifier/identifiers.go
- test-network-function/diagnostic/suite.go
- test-network-function/identifiers/identifiers.go
- test-network-function/suite_test.go
add listing 3rd party CSI drivers info to diagnostic test
> List all installed CSI drivers info from cluster CNFCERT24-item 1

- .github/workflows/pre-main.yaml
Did this change together with Salah.
> Add operator to the container run in CI workflow

- README.md
- pkg/config/autodiscover/autodiscover.go
- pkg/config/autodiscover/autodiscover_partner.go
- pkg/config/autodiscover/autodiscover_targets.go
- pkg/config/autodiscover/csv_info.go
- pkg/config/autodiscover/pod_info.go
- pkg/config/config.go
- pkg/config/configsections/common.go
- test-network-function/networking/suite.go
- test-network-function/tnf_config.yml
skip networking tests if no orchestrator is found
> add namespace support

- pkg/config/config.go
- pkg/tnf/interactive/spawner.go
- pkg/tnf/interactive/spawner_test.go
reading the stderr pipe of spawned commands and displaying as a warning in logger
> Adding stderr to logger

- Dockerfile
- README.md
- cmd/catalog/cmd/generate.go
- cmd/claim/main.go
- go.mod
- pkg/config/autodiscover/csv_info_test.go
- pkg/config/autodiscover/deployment_info_test.go
- pkg/config/autodiscover/pod_info_test.go
- pkg/config/config.go
- pkg/config/configsections/certified_request_test.go
- pkg/config/configsections/config_section_test.go
- pkg/jsonschema/utils.go
- pkg/tnf/handlers/generic/assertion/assertions_test.go
- pkg/tnf/handlers/generic/generic.go
- pkg/tnf/handlers/generic/resultcontext_test.go
- pkg/tnf/handlers/ipaddr/ipaddr_test.go
- pkg/tnf/handlers/ping/ping_test.go
- pkg/tnf/identifier/identifier_test.go
- pkg/tnf/interactive/pty.go
- pkg/tnf/testcases/base.go
- pkg/tnf/testcases/base_test.go
- test-network-function/suite_test.go
- test-network-function/version/version.go
https://golang.org/doc/go1.16
Checking to see if this passes the GitHub automated checks.
> Go 1.16 Upgrade

- DEVELOPING.md
- pkg/tnf/test.go
- run-cnf-suites.sh
- test-network-function/lifecycle/suite.go
- test-network-function/platform/suite.go
This is a fix for a filtering bug after ginkgo v2 / claim log PR. Also removes deprecation warnings
> Fix for Ginkgo v2 deprecation warnings and filtering bug

- CATALOG.md
- cmd/tnf/generate/catalog/catalog.go
update the missing best practice changes
> update the best practice

- Makefile
- README.md
- internal/api/api.go
- internal/api/api_test.go
- pkg/config/autodiscover/deployment_info.go
- pkg/config/configsections/certified_request_test.go
- pkg/config/configsections/config_section_test.go
- pkg/gradetool/gradetool.go
- pkg/tnf/testcases/base.go
- pkg/tnf/testcases/base_test.go
https://github.com/golangci/golangci-lint/releases/tag/v1.43.0
The linter raised some various fixes that needed addressing as well.
> GolangCI v1.43.0; various fixes

- pkg/config/autodiscover/autodiscover.go
- pkg/config/autodiscover/autodiscover_partner_test.go
- pkg/config/autodiscover/autodiscover_test.go
- pkg/config/autodiscover/testdata/testpods_empty.json
- pkg/config/autodiscover/testdata/testpods_withlabel.json
Marked WIP as I add more coverage.
> Add more test coverage to autodiscover

- pkg/tnf/handlers/clusterrolebinding/clusterrolebinding.go
- pkg/tnf/handlers/clusterversion/clusterversion.go
- pkg/tnf/handlers/deployments/deployments.go
- pkg/tnf/handlers/deploymentsdrain/deploymentsdrain.go
- pkg/tnf/handlers/deploymentsnodes/deploymentsnodes.go
- pkg/tnf/handlers/hugepages/hugepages.go
- pkg/tnf/handlers/nodenames/nodenames.go
- pkg/tnf/handlers/nodetainted/nodetainted.go
- pkg/tnf/handlers/owners/owners.go
- pkg/tnf/handlers/rolebinding/rolebinding.go
- pkg/tnf/handlers/scaling/scaling.go
- pkg/tnf/handlers/scaling/scaling_hpa.go
- pkg/tnf/handlers/serviceaccount/serviceaccount.go
> More typo cleanup

- pkg/tnf/test.go
- test-network-function/accesscontrol/suite.go
Wrapper function over the GinkgoWriter, to make it easier for adding extra error/debugging information so TCs can be fixed/debugged.
> Added claim file logger function in tnf (test.go) package

- test-network-function/diagnostic/suite_test.go
Replacement for #520 
This just adds some tests, no functional changes to the `init` variables.
> Add unit tests for diagnostic suite

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
https://go.dev/doc/devel/release#go1.17
> Update Go to 1.17.5

- test-network-function/lifecycle/suite.go
This commit:
* Avoids stopping the test case in testImagePolicy(), testShutdown()
and testOwnder() if one pod fails
* Simplifies logging in some cases, using tnf.ClaimFilePrintf()
* Tries to makes sure all lifecycle tests add some meaningful information
to the claim file in case of a failure.
> lifecycle: improve logging, test all pods if one fails

- .golangci.yml
> Missed version upgrade; 1.43.x

- CATALOG.md
- test-network-function/identifiers/identifiers.go
- test-network-function/lifecycle/suite.go
update statefulset scaling identifier
> update statefulset scaling identifier

- CATALOG.md
[1] missed the catalog update as part of its fixes.
[1] - https://github.com/test-network-function/test-network-function/pull/553
> Update platform-alteration/sysctl-config in CATALOG.md

- test-network-function/diagnostic/suite.go
Previously, only the CNI plugin name was stored in the claim file (the
version was obtained but not published). This commit improves this by
collecting the plugins for each CNI, and properly storing the version
and plugins in the claim file.
> Improve CNI plugin collection

- pkg/tnf/interactive/oc.go
- test-network-function/platform/suite.go
Shimrit also needs this for the listening port command
> Expose the interactive context from Oc

- pkg/config/autodiscover/csv_info_test.go
- pkg/config/autodiscover/testdata/csv_output.json
- pkg/config/autodiscover/testdata/csv_output_nolabel.json
Adding some more coverage for the autodiscover/csv_info functions.
> Add tests for csv_info.go

- Dockerfile
> Fix missed Go 1.17.5 upgrade

- pkg/config/config_test.go
The functions I didn't cover are using the Expecter and I'm not sure how I would go about unit testing those at this time.
> Add unit tests for config.go

- .github/workflows/pre-main.yaml
The current code coverage is up over 70%+.  I'm bumping the minimum threshold to 70% as we continue to improve our unit testing.
> Bump coverage threshold to 70%

- cmd/tnf/addclaim/addclaim.go
> Fix simple typo

- pkg/config/autodiscover/autodiscover_debug_test.go
- pkg/config/autodiscover/testdata/pods_with_debug_label.json
- pkg/config/configsections/container_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
`FindDebugPods` was the missing unit tests.
There are a few other functions in that file, but they are using the `tnf.NewTest` function and I'm not sure how to unit test that at this time.
> Add unit test for FindDebugPods

- Makefile
> Fix install-tools path

- pkg/config/config.go
- test-network-function/accesscontrol/suite.go
- test-network-function/accesscontrol/suite_test.go
- test-network-function/lifecycle/suite.go
- test-network-function/platform/suite.go
* Adding unit tests.
* Removing unnecessary local variables in some funcs.
* Using `StringInSlice` to remove some lookup loops.
> Add accesscontrol tests

- .github/workflows/tnf-image.yaml
- Need to test image that corresponds to the right branch
- CLI needs to work for all versions built by the script
> adding 3.3.x branch to the image building and bugfix

- .github/workflows/tnf-image.yaml
Forcing the matrix steps to perfom sequentially so that the lastes release is labelled the latest as "latest"
> Forcing sequential actions in matrix

- pkg/tnf/handlers/podsets/podsets.go
> More typos

- pkg/utils/utils.go
Switch case learning opportunity in go
> Fix for bug in networking latest PR

- Makefile
> Bump install-tools ginkgo to v2.1.3

- Makefile
- README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.44.2
> Upgrade GolangCI-lint to v1.44.2

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
https://groups.google.com/g/golang-announce/c/RP1hfrBYVuk/m/I7ouYouLAAAJ
Similar to:
- https://github.com/test-network-function/cnfcert-tests-verification/pull/47
- https://github.com/test-network-function/cnf-certification-test/pull/51
- https://github.com/test-network-function/test-network-function-claim/pull/39
- https://github.com/test-network-function/cnf-certification-test-partner/pull/88
> Update Go to 1.17.8

- Dockerfile
https://github.com/helm/helm/releases/tag/v3.8.1
> Bump Helm to 3.8.1

- .github/workflows/pre-main.yaml
- test-network-function/certification/suite.go
currently test new partner repo with old tnf
> Porting of Fail operator cert test if operator is not certified #95

- pkg/config/autodiscover/autodiscover_debug.go
+ Retry interval also increased to 5 secs.
> Timeout for debug pods increased to 5mins.

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
https://github.com/golang/go/issues?q=milestone%3AGo1.17.9+label%3ACherryPickApproved
> Update Go to 1.17.9

- .github/workflows/pre-main.yaml
- .github/workflows/tnf-image.yaml
https://releases.ubuntu.com/22.04/
LTS 22.04 is available "Jammy Jellyfish".
> Upgrade Ubuntu release to 22.04
